version: "3.8"
networks:
  kafka-net:
    ipam:
      config:
        - subnet: 192.168.220.0/24
services:
  kafka1:
    container_name: kafka1
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9092:9092"
    networks:
      kafka-net:
        ipv4_address: 192.168.220.140
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: kafka2
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9292:9092"
    networks:
      kafka-net:
        ipv4_address: 192.168.220.141
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: kafka3
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9392:9092"
    networks:
      kafka-net:
        ipv4_address: 192.168.220.142
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/